MADescriptionTruncater
Assargadon/magritte-python pull request #145
Opened 2024-12-09 19:18 UTC by konstantin-kalinin-wizn-tech

2024-12-09 19:20 UTC, konstantin-kalinin-wizn-tech commented
Связан с https://github.com/passimens/magritte-js/pull/11

2024-12-10 12:58 UTC, Assargadon requested changes

2024-12-10 12:58 UTC, Assargadon commented on Magritte/visitors/MADescriptionTruncater_visitors.py
Неясно, почему в названии файла употреблено множественное число.
Изначально предполагалось, что truncater'ов будет несколько?

2024-12-10 12:58 UTC, Assargadon commented on Magritte_DescriptionTranspiler/MADescriptionTranspiler_JS.py
> +        description_names_whitelist=['Host', 'Port', 'SoftwarePackage'],
Не совсем понял причину расширения этого "демонстрационного списка" - ведь truncater в этом файле не используется?

Или это ты что-то "заодно" делаешь?

2024-12-10 12:58 UTC, Assargadon commented on Magritte/visitors/MADescriptionTruncater_visitors.py
> +            self._truncated_description = description
Тут _по логике_ надо сказать `visitElementDescription` (по сути он здесь и заинлайнен)

2024-12-10 12:58 UTC, Assargadon commented on Magritte/visitors/MADescriptionTruncater_visitors.py
> +    def visitSingleOptionDescription(self, description: MAReferenceDescription):
Эту логику хорошо бы переместить прямо на уровень `visitReferenceDescription`.
Да ещё заинлайнить содержимое `visitRelationDescription`.

Чтоб получилось что-то типа
```
def visitReferenceDescription(...):
        isContainer = isinstance(description.reference, MAContainer)
        if isContainer:
            // код из visitRelationDescription(description)
        else:
            visitElementDescription(description)
```
Тогда, например, `visitMultipleOptionDescription` (которого ещё нет, но который планируется) "сам собой"  обработается. Как и `ToManyRelationDescription` с не-MAContainer'ным описанием ("массив из интов"). Мы покамест тоже такое не поддерживаем - но хотим.

2024-12-10 12:58 UTC, Assargadon commented on Magritte/visitors/tests/MADescriptionTruncater_test.py
> +        provider = TestEnvironmentProvider()
предлагаю переименовать в `environment`, если уж предыдущая строчка - `descriptors`

2024-12-10 12:58 UTC, Assargadon commented on Magritte/visitors/tests/MADescriptionTruncater_test.py
> +    def _performPasstrough(self, model, description, pathes_whitelist):
Можно я попрошу переименовать это во что-нибудь вроде `_performSerializationRoundtrip` ?

2024-12-10 13:06 UTC, konstantin-kalinin-wizn-tech commented on Magritte_DescriptionTranspiler/MADescriptionTranspiler_JS.py
> +        description_names_whitelist=['Host', 'Port', 'SoftwarePackage'],
Это я делал тестовые js-дескрипторы.

2024-12-10 13:29 UTC, konstantin-kalinin-wizn-tech commented on Magritte/visitors/MADescriptionTruncater_visitors.py
Разброд и шатание.

MADescriptionTruncater**_visitors**.py
MAEqualityTester**_visitor**.py
MAJson**_visitors**.py
MAReferencedDataWriterReader**_visitors**.py
MAStringWriterReader_visitors.py
MAValidatorVisitor**_class**.py
MAVisitor**_class**.py

2024-12-10 19:29 UTC, Assargadon commented on Magritte/visitors/MADescriptionTruncater_visitors.py
Неа, не такой уж разброд. В `MADescriptionTruncater _visitors.py`, ` MAJson _visitors.py` и ` MAStringWriterReader _visitors.py` - по несколько визиторов. Классически - пара на чтение и на запись, но прибавляются всякие общие предки, вспомогательные и т.п. Потому и visitor**s** - визиторы, объединённые определенной "темой".

А в ` MAEqualityTester _visitor.py` - визитор, действительно, один.

2024-12-11 00:52 UTC, merged